n_levels: 2

aggregate: max
norm: batch
actv: relu
res: true

in_conv: mr
in_dim: 64
in_radius: 0.015
in_k: 16

block: mr
scale_factor: [4, 4]
dims: [128, 256]
depth: [1, 1]
radius: [[[0.015, 0.025]], [[0.025, 0.05]]]
k: [[[16, 16]], [[16, 16]]]

out_relu: false
up: linear